# Generated by Django 4.2.7 on 2023-12-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_favourite_user_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='featured_image',
            field=models.ImageField(blank=True, default='Images/default.jpg', null=True, upload_to='recipes_images/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='Images/profile_images/user-default.png', null=True, upload_to='profile_images/'),
        ),
    ]
