# Generated by Django 4.2.7 on 2023-12-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_featured_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='featured_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='recipes_images/'),
        ),
    ]
